dist: xenial

sudo: required

language: bash

before_install:
  - sudo apt-get update

script:
  - bash scripts/download-raspbian.sh
  - sudo bash scripts/extend-raspbian.sh
  - sudo bash scripts/mount-raspbian.sh
